---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r}
data("ny_noaa")

ny_noaa = 
  ny_noaa %>% 
  select(-tmax, -tmin) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Observation of precipitation of selected Weather Stations

```{r}
prcp = 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  filter(!is.na(prcp),
         year == 2010) %>% 
  group_by(id) %>% 
  summarize(n = n()) %>% 
  filter(n > 50 & n < 100)  

left_join(prcp, ny_noaa, by = "id") %>% 
  filter(!(id %in% c("USC00307818", "USC00300048", "US1NYTG0017", "US1NYAB0017","US1NYHM0001","US1NYOG0025","US1NYTM0006","US1NYSF0018","US1NYCY0005","US1NYST0029", "US1NYSR0013"))) %>% 
  mutate(id = fct_reorder(id, prcp)) %>% 
  plot_ly(y = ~prcp, color = ~id, type = "box", colors = "viridis") %>% 
  layout(yaxis = list(title = "Precipitation(tenths of mm)"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Precipitation of CentralPark_NY across time

```{r}
ny_noaa %>%
  filter(id == "USW00094728",
         !is.na(prcp)) %>% 
  mutate(
    text_label = str_c("Date: ", date, "\nPrecipitation (tenths of mm): ", prcp)
  ) %>% 
  plot_ly(
    x = ~date, y = ~prcp, type = "scatter", mode = "markers",
    text = ~text_label, alpha = 0.5) %>% 
  layout(xaxis = list(title = "Time"),
        yaxis = list(title = "Precipitation"))
```

### Snowfall of CentralPark_NY across time

```{r}
ny_noaa %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  filter(id == "USW00094728",
         !is.na(snow)) %>% 
  group_by(id, year) %>% 
  summarize(n = sum(snow)) %>% 
  plot_ly(x = ~year, y = ~n, type = "bar", colors = "viridis") %>% 
  layout(xaxis = list(title = "Year"),
        yaxis = list(title = "Snowfall(mm)"))
```

